### PR TITLE
Check Minio server is up after (re)start

### PR DESCRIPTION
**Pull request by sberthier**

### CODE REVIEW

**Comment by SuperQ** [comment]
This seems unnecessary.

* Typically your monitoring system would be watching for problems.
* There's no action to be taken, it just creates an error.

**Comment by sberthier** [comment]
Yes, monitoring system should raise minio errors. But it may be good to know that's because an ansible playbook failed. And effectively, there is not action to fixed that (just wake up humans).

**Comment by SuperQ** [comment]
This seems out of scope for Ansible.

**Comment by sberthier** [comment]
ok, I close this PR.

**Pull request closed without merging**
